default:
  - _self_
  - model: model0

Data:
  path: str = "data/"
  truncate: float = 1.0
  batch_size: int = 256
  block_size: int = 256

Args:
  save_every: int = 64
  total_epochs: int = 10000
  snapshot_path: str = "snapshot/snapshot.pt"
